### ISSUE TITLE
uri filter out

### ISSUE THREAD

**Issue by mrafieee** [calvinlfer/skull-island#5]
I have an endpoint with Host but not URI and it is getting filtered out 
Kong is supporting either hosts, uri or method

**Comment by calvinlfer** [comment]
Can you give me some examples 😸

**Comment by calvinlfer** [comment]
Hey @mrafieee, 

I tried out an API configuration like this:
```json
apis: [
      {
        "hosts": [
          "example.com"
        ],
        "upstream_url": "http://getkong.org",
        "name": "calvin-kong-test"
      }
]
```

This creates the the API on Kong without performing any filtering:
![image](https://user-images.githubusercontent.com/14280155/27888636-2222a5d4-61b5-11e7-9393-e09fd4016a47.png)

`GET <Kong Proxy URL>/` providing headers `Host: example.com` will visit the upstream URL.

Have you included a valid `upstream_url` that begins with `http`? 
That would be the reason for an API to be filtered out from the synchronization process

**Comment by calvinlfer** [comment]
@mrafieee I'm closing this but feel free to re-open it if you still have trouble
